// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNwnDXdX7zSLmGV3F1Gh5hmZFjzBiGD0I',
    appId: '1:113412083891:web:395f107f50e3d01b4ee0c6',
    messagingSenderId: '113412083891',
    projectId: 'manager--meet',
    authDomain: 'manager--meet.firebaseapp.com',
    storageBucket: 'manager--meet.appspot.com',
    measurementId: 'G-GYW5YFF7L3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTsODWy1cK0H8jxm4NGT-R_G9EiTo7vfI',
    appId: '1:113412083891:android:2c5ab12628bade1a4ee0c6',
    messagingSenderId: '113412083891',
    projectId: 'manager--meet',
    storageBucket: 'manager--meet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0MRKdPXrppkRNZPwwRr8f382GM3cXH8U',
    appId: '1:113412083891:ios:b56b6d21185595484ee0c6',
    messagingSenderId: '113412083891',
    projectId: 'manager--meet',
    storageBucket: 'manager--meet.appspot.com',
    iosBundleId: 'com.example.managerGoogleMeet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0MRKdPXrppkRNZPwwRr8f382GM3cXH8U',
    appId: '1:113412083891:ios:276c97979389e7694ee0c6',
    messagingSenderId: '113412083891',
    projectId: 'manager--meet',
    storageBucket: 'manager--meet.appspot.com',
    iosBundleId: 'com.example.managerGoogleMeet.RunnerTests',
  );
}
